### ISSUE TITLE
Comparison Modal: UI  - no intuitive way to exit modal

### ISSUE THREAD

**Issue by chenyou-H** [gentoopenguinparty/SpeedyPenguinProject#51]
https://github.com/gentoopenguinparty/SpeedyPenguinProject/blob/3e23ad5cee68c3aa76bc8b470568cfdac02fd334/src/RelatedItemsOutfits/ComparisonModal.jsx#L18-L33

**Description**
There is not an intuitive way to exit modal. The user may not know how to exit the modal without a UI component

**Screenshots**
<img width="610" alt="Modal" src="https://user-images.githubusercontent.com/57925563/180611373-6164047d-2d45-4714-8bd8-919889a4442e.png">

**Files**
ComparisonModal.jsx

**To Reproduce**
Click the star button (CompareProductButton) to open the modal

**Task**

- [ ] create a exit button in the modal

**Comment by code402b** [comment]
Thanks for the feedback. In this case, I think that it looks cleaner without a button to exit. I feel that clicking outside the modal to dismiss is a fairly well understood UI convention.
